In [1]:
# "Smaller the angle, the higher the similarity” — Cosine Similarity.

In [2]:
# Understanding Cosine Similarity between Two Sentences

# Step 1: Find the Counter Vectorizer the document
# Step 2: find cosine_similarity of two vectors from the Documents

In [3]:
doc1 = "Julie loves John more than Linda loves John"
doc2 = "Jane loves John more than Julie loves John"

doc = [doc1,doc2]

vocab = []

doc

['Julie loves John more than Linda loves John',
 'Jane loves John more than Julie loves John']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
# create the transform
vectorizer = CountVectorizer()

# tokenize and build vocab
vectorizer.fit(doc)

# summarize
print(vectorizer.vocabulary_)

{'julie': 2, 'loves': 4, 'john': 1, 'more': 5, 'than': 6, 'linda': 3, 'jane': 0}


In [6]:
vector = vectorizer.transform(doc)
vector.toarray()

array([[0, 2, 1, 1, 2, 1, 1],
       [1, 2, 1, 0, 2, 1, 1]], dtype=int64)

In [7]:
d1 = vector.toarray()[0,:]

d2 = vector.toarray()[1,:]

print("d1:",d1)
print("d2:",d2)

d1: [0 2 1 1 2 1 1]
d2: [1 2 1 0 2 1 1]


In [8]:
d1 = d1.reshape(1,-1)
d2 = d2.reshape(1,-1)

In [9]:
d1

array([[0, 2, 1, 1, 2, 1, 1]], dtype=int64)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(d1,d2)

array([[0.91666667]])

In [11]:
# The cosine angle (the smaller the angle) between the two vectors' value is 0.9166 which is nearest to 1.

In [24]:
# Example 2: using Count Vectorization


import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()

print("Step 1: Get the coupus Data")
data = ['Julie loves me more than Linda loves me','Jane likes me more than Julie loves me']

print("\n")
print("Step 2: Build the vector matrix using counter vectorizers")
vocabulary=vectorizer.fit(data)
X= vectorizer.transform(data)

print(X.toarray())
print(vocabulary.get_feature_names())

vec1 = X.toarray()[0,:]
print("vec1={0}".format(vec1))

vec2 = X.toarray()[1,:]
print("vec2={0}".format(vec2))

vec1 = vec1.reshape(1,-1)
vec2 = vec2.reshape(1,-1)

print("\n")
print("Step 3: Find Similarity between sentences using cosine_similarity")
from sklearn.metrics.pairwise import cosine_similarity
cosine_similaritylist(vec1),list(vec2))

SyntaxError: invalid syntax (<ipython-input-24-f9b8f6537f8a>, line 32)

In [21]:
# Example 3: using TFIDF Vectorization

pair1 = ["What you do defines you",
         "Yours deeds defines you"]

pair2 = ["Once upon a time there lived a king.",
         "Who is your queen?"]

pair3 = ["He is desperate",
         "Is he not desperate?"]

print("Step 1: Get the corpus data")
corpus = [pair1[0],pair1[1],pair2[0],pair2[1],pair3[0],pair3[1]]

print("Corpus :",corpus)

print("\n")
print("Step 2: Build the Vector matrix using TFSIDF")
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_model = TfidfVectorizer()
tfidf_results = tfidf_model.fit_transform(corpus).todense()

#print(tfidf_results.shape)

print(tfidf_results[0])
print("\n")
print(tfidf_results[1])


print("\n")
print("Step 3:Find the Cosine Similarity between sentences")
print("Similarity Between Sentence1 and Sentence2:",cosine_similarity(tfidf_results[0],tfidf_results[1]))
print("Similarity Between Sentence3 and Sentence4:",cosine_similarity(tfidf_results[2],tfidf_results[3]))
print("Similarity Between Sentence5 and Sentence6:",cosine_similarity(tfidf_results[4],tfidf_results[5]))

Step 1: Get the corpus data
Corpus : ['What you do defines you', 'Yours deeds defines you', 'Once upon a time there lived a king.', 'Who is your queen?', 'He is desperate', 'Is he not desperate?']


Step 2: Build the Vector matrix using TFSIDF
[[0.         0.3541223  0.         0.43184893 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.43184893 0.         0.7082446  0.
  0.        ]]


[[0.54677906 0.44836665 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.44836665 0.
  0.54677906]]


Step 3:Find the Cosine Similarity between sentences
Similarity Between Sentence1 and Sentence2: [[0.47632989]]
Similarity Between Sentence3 and Sentence4: [[0.]]
Similarity Between Sentence5 and Sentence6: [[0.80368547]]


In [14]:
# Example 3:

import nltk 
from nltk.cluster.util import cosine_distance

print("Step1 :","Get the sentences")
sent1 = "Hi how are you"
sent2 = "Hi i am fine"
print("Sent1:",sent1)
print("Sent2:",sent2)

print("\n")


print("Step2 :","Tokenize the sentences")

tokenized_sent1 = nltk.tokenize.word_tokenize(sent1)
tokenized_sent2 = nltk.tokenize.word_tokenize(sent2)

print("tokenized_sent1:",tokenized_sent1)
print("tokenized_sent2:",tokenized_sent2)

print("\n")
print("Step3 :","Get all the words")
# List all the words
all_words = list(set(sent1 + sent2))
print("All words:",all_words)

# Create Vector
vector1 = [0] * len(all_words)
vector2 = [0] * len(all_words)

# Get the word Frequency
for w in sent1:
    vector1[all_words.index(w)] +=1
    
for w in sent2:
    vector2[all_words.index(w)] +=1
    
print("\n")

print("Step 4: Transofrm docs to Vector")
print("vector1:",vector1)
print("vector2:",vector2)

print("\n")
print("Step 5: Find the Cosine Similarity")
cosine_distance(vector1,vector2)
print("Cosine Distance Between two vectors:",cosine_distance(vector1,vector2))

Step1 : Get the sentences
Sent1: Hi how are you
Sent2: Hi i am fine


Step2 : Tokenize the sentences
tokenized_sent1: ['Hi', 'how', 'are', 'you']
tokenized_sent2: ['Hi', 'i', 'am', 'fine']


Step3 : Get all the words
All words: ['w', 'r', 'y', 'H', 'f', 'u', 'h', ' ', 'i', 'n', 'e', 'a', 'o', 'm']


Step 4: Transofrm docs to Vector
vector1: [1, 1, 1, 1, 0, 1, 1, 3, 1, 0, 1, 1, 2, 0]
vector2: [0, 0, 0, 1, 1, 0, 0, 3, 3, 1, 1, 1, 0, 1]


Step 5: Find the Cosine Similarity
Cosine Distance Between two vectors: 0.34720879016613315


In [26]:
# Example 4: Cosine Similariry for the Dataframe

# Define the documents
doc_trump = "Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career"

documents = [doc_trump, doc_election, doc_putin]

print("\n")

print("Step 1: Build Document vetcor")
print(documents)

# To compute the cosine similarity, you need the word count of the words in each document. 
# The CountVectorizer or the TfidfVectorizer from scikit learn lets us compute this. 
# The output of this comes as a sparse_matrix

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

print("\n")
print("Step 2 : Build vectorizer using countvectorizer")
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)

doc_term_matrix = sparse_matrix.todense()

print(doc_term_matrix)

print("\n")
print("Step 3 : Build Data frame for counter vectorizer for the doucments")
df = pd.DataFrame(doc_term_matrix, columns=count_vectorizer.get_feature_names(),index=['doc_trump', 'doc_election', 'doc_putin'])
print(df)

print("\n")

print("Step 4 : Find the cosine Similarity Matrix for the data frame")
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))



Step 1: Build Document vetcor
['Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin', 'President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election', 'Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career']


Step 2 : Build vectorizer using countvectorizer
[[1 0 1 0 0 0 0 0 1 0 0 2 0 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 2 0 1 1 0 0 0
  1 1 2 1 0 2 0 0 0 1 0 1]
 [0 0 0 1 0 1 1 0 2 0 1 0 2 2 0 0 1 2 1 0 0 0 1 1 0 1 1 2 0 2 0 2 0 0 2 0
  0 0 2 0 1 1 0 1 1 0 1 1]
 [0 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 1 2 1 2 0 1 0 1
  0 0 1 0 0 0 1 0 0 0 0 0]]


Step 3 : Build Data frame for counter vectorizer for the doucments
              after  as  be

In [25]:
# Build sentence_Similarity Matrix

import pandas as pd
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords

file = open("C:\MyWork\MyLearning\Career Growth\ML\Files\DataSet\SampleText01.txt",'r')

text = file.read()

print("Step 1: Read the corpus Data")
print(text)

text = text.replace("[^a-zA-z]",'')
stopword = stopwords.words('english')

print("\n")
print("Step 2: Sentence Tokenize the Corpus")
sentences = sent_tokenize(text)

print(sentences)

print("\n")

def sentence_similarity(sent1,sent2):
    sent1 = word_tokenize(sent1.lower())
    sent2 = word_tokenize(sent2.lower())

    all_words = list(set(sent1 + sent2))

    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    
    for w in sent1:
        if w in stopword:
            continue
        vector1[all_words.index(w)] +=1
    
    for w in sent2:
        if w in stopword:
            continue
        vector2[all_words.index(w)] +=1
        
    return  1 - cosine_distance(vector1,vector2)

def build_similarity_matrix(sentences):
    similarity_matrix = np.zeros((len(sentences), len(sentences)))
    
    for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
            #if idx1 == idx2:
                #continue
            similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1],sentences[idx2])
            
    return similarity_matrix


print("Step 3: Build similarity matrix")

pd.DataFrame(build_similarity_matrix(sentences),columns=['Sent1','Sent2','Sent3','Sent4','Sent5','Sent6','Sent7','Sent8','Sent9','Sent10','Sent11'],
              index=['Sent1','Sent2','Sent3','Sent4','Sent5','Sent6','Sent7','Sent8','Sent9','Sent10','Sent11'])

Step 1: Read the corpus Data
In an attempt to build an AI-ready workforce, Microsoft announced Intelligent Cloud Hub which has been launched to empower the next generation of students with AI-ready skills. Envisioned as a three-year collaborative program, Intelligent Cloud Hub will support around 100 institutions with AI infrastructure, course content and curriculum, developer support, development tools and give students access to cloud and AI services. As part of the program, the Redmond giant which wants to expand its reach and is planning to build a strong developer ecosystem in India with the program will set up the core AI infrastructure and IoT Hub for the selected campuses. The company will provide AI development tools and Azure AI services such as Microsoft Cognitive Services, Bot Services and Azure Machine Learning.According to Manish Prakash, Country General Manager-PS, Health and Education, Microsoft India, said, "With AI being the defining technology of our time, it is tran

Sent1     Sent2     Sent3     Sent4     Sent5     Sent6     Sent7  \
Sent1   1.000000  0.319438  0.175412  0.218218  0.091287  0.129099  0.239046   
Sent2   0.319438  1.000000  0.336199  0.557657  0.174964  0.247436  0.076360   
Sent3   0.175412  0.336199  1.000000  0.229668  0.160128  0.113228  0.209657   
Sent4   0.218218  0.557657  0.229668  1.000000  0.199205  0.112687  0.052164   
Sent5   0.091287  0.174964  0.160128  0.199205  1.000000  0.235702  0.109109   
Sent6   0.129099  0.247436  0.113228  0.112687  0.235702  1.000000  0.077152   
Sent7   0.239046  0.076360  0.209657  0.052164  0.109109  0.077152  1.000000   
Sent8   0.279508  0.178571  0.196116  0.073193  0.102062  0.144338  0.200446   
Sent9   0.230940  0.295084  0.253185  0.352767  0.210819  0.149071  0.138013   
Sent10  0.134164  0.114286  0.156893  0.097590  0.163299  0.115470  0.106904   
Sent11  0.167705  0.214286  0.294174  0.170783  0.306186  0.216506  0.200446   

           Sent8     Sent9    Sent10    Sent11  
Sent1   0.279508  0.230940  0.134164  0.167705  
Sent2   0.178571  0.295084  0.114286  0.214286  
Sent3   0.196116  0.253185  0.156893  0.294174  
Sent4   0.073193  0.352767  0.097590  0.170783  
Sent5   0.102062  0.210819  0.163299  0.306186  
Sent6   0.144338  0.149071  0.115470  0.216506  
Sent7   0.200446  0.138013  0.106904  0.200446  
Sent8   1.000000  0.129099  0.200000  0.250000  
Sent9   0.129099  1.000000  0.154919  0.258199  
Sent10  0.200000  0.154919  1.000000  0.300000  
Sent11  0.250000  0.258199  0.300000  1.000000

In [36]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity

print("Step1: Get the docoument data")
pair1 = ["What you do defines you","Yours deeds defines you"]
pair2 = ["Once upon a time there lived a king.","Who is your queen?"]
pair3 = ["He is desperate","Is he not desperate?"]

print("\nStep2: Get the couspus data")
corpus = [pair1[0],pair1[1],pair2[0],pair2[1],pair3[0],pair3[1]]
print(corpus)

print("\nStep3: Build the Vector matrix using TfidfVectorizer")
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_model = TfidfVectorizer()
tfidf_results = tfidf_model.fit_transform(corpus).todense()
print(tfidf_results)

print("\nStep 4: Find Senetnce Similarity Using Cosine Similarity")
print(cosine_similarity(tfidf_results[0],tfidf_results[1]))
print(cosine_similarity(tfidf_results[2],tfidf_results[3]))
print(cosine_similarity(tfidf_results[4],tfidf_results[5]))


Step1: Get the docoument data

Step2: Get the couspus data
['What you do defines you', 'Yours deeds defines you', 'Once upon a time there lived a king.', 'Who is your queen?', 'He is desperate', 'Is he not desperate?']

Step3: Build the Vector matrix using TfidfVectorizer
[[0.         0.3541223  0.         0.43184893 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.43184893 0.         0.7082446  0.
  0.        ]
 [0.54677906 0.44836665 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.44836665 0.
  0.54677906]
 [0.         0.         0.         0.         0.         0.
  0.40824829 0.40824829 0.         0.40824829 0.         0.40824829
  0.40824829 0.40824829 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.37115593
  0.         0.         0.         0.         0.53611046 0.
  0.     