In [6]:
#Importing the required modules
import numpy as np
from nltk.tokenize import word_tokenize
from collections import defaultdict 

#Sample text corpus
data = ['She loves pizza, pizza is delicious.',
        'She is a good person.',
        'good people are the best.']

#clean the corpus.
sentences = []
vocab = []
for sent in data:
    x = word_tokenize(sent)
    sentence = [w.lower() for w in x if w.isalpha() ]
    sentences.append(sentence)
    for word in sentence:
        if word not in vocab:
            vocab.append(word)
 
#number of words in the vocab
len_vector = len(vocab)

vocab

['she',
 'loves',
 'pizza',
 'is',
 'delicious',
 'a',
 'good',
 'person',
 'people',
 'are',
 'the',
 'best']

In [5]:
#Index dictionary to assign an index to each word in vocabulary

index_word = {}
i = 0
for word in vocab:
    index_word[word] = i 
    i += 1

In [7]:
# Define the Bag of Words model function

def bag_of_words(sent):
    count_dict = defaultdict(int)
    vec = np.zeros(len_vector)
    for item in sent:
        count_dict[item] += 1
    for key,item in count_dict.items():
        vec[index_word[key]] = item
    return vec  

In [8]:
vector = bag_of_words(sentences[0])
print(vector)

[1. 1. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
vector = bag_of_words(sentences[1])
print(vector)

[1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0.]


In [10]:
vector = bag_of_words(sentences[2])
print(vector)

[0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1.]


In [19]:
[list(bag_of_words(x)) for x in sentences]

[[1.0, 1.0, 2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0]]