### Simple List

In [19]:
def one_hot_encode_my_word(myword,the_vocabulary):
    one_hot_encode_vector = []
    for word in the_vocabulary:
        if word == myword:
            one_hot_encode_vector.append(1)
        else:
            one_hot_encode_vector.append(0)
    return one_hot_encode_vector

v = ["duct", "tape", "works", "anywhere", "is", "magic", "and", "should", "be", "worshiped"]

for i in range(0,len(v)):
    print(v[i] + ": \t" +str(one_hot_encode_my_word(v[i],v)))

duct: 	[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
tape: 	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
works: 	[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
anywhere: 	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
is: 	[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
magic: 	[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
and: 	[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
should: 	[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
be: 	[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
worshiped: 	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


### Using Pandas 'get_dummies'

In [20]:
import pandas as pd

df = pd.DataFrame(['S','C','Q','S','S','C','Q','Q','C','S'],columns=['Embarked'])

print(df.head())

pd.get_dummies(df, columns=["Embarked"]).head()

  Embarked
0        S
1        C
2        Q
3        S
4        S


Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           1           0
3           0           0           1
4           0           0           1

### Example 01

In [21]:
import numpy as np

docs = "Thanks for an excellent report".lower().split()
doc1 = set(docs)
doc1 = sorted(doc1)
print ("\nvalues: ", doc1)

integer_encoded = []
for i in docs:
    v = np.where( np.array(doc1) == i)[0][0]
    integer_encoded.append(v)
print ("\ninteger encoded: ",integer_encoded)

def get_vec(len_doc,word):
    empty_vector = [0] * len_doc
    vect = 0
    find = np.where( np.array(doc1) == word)[0][0]
    empty_vector[find] = 1
    return empty_vector

def get_matrix(doc1):
    mat = []
    len_doc = len(doc1)
    for i in docs:
        vec = get_vec(len_doc,i)
        mat.append(vec)
        
    return np.asarray(mat)

print ("\nMATRIX:")
print (get_matrix(doc1))


values:  ['an', 'excellent', 'for', 'report', 'thanks']

integer encoded:  [4, 2, 0, 1, 3]

MATRIX:
[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]


### Example 02

In [2]:
import pandas as pd

train = [("Thanks for an excellent report", "pos"),
         ("Your service is very quick and fast", "pos"),
        ("I am pleased with your service", "pos"),
        ("I did not know i was diabetic until you gave me this report", "neg"),
        ("Service - Little slow, probably because too many people.", "neg"),
        ("The place is not easy to locate", "neg"),
        ("The place is very easy to locate", "pos"),
        ("Not satisfied will take a second opinion", "neg"),
        ("No human contact everything is so robotic here", "neg")]

df = pd.DataFrame(train,columns=['review','sentiment'])

df.head()

review sentiment
0                     Thanks for an excellent report       pos
1                Your service is very quick and fast       pos
2                     I am pleased with your service       pos
3  I did not know i was diabetic until you gave m...       neg
4  Service - Little slow, probably because too ma...       neg

In [3]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stopwords = stopwords.words('english')

In [4]:
data = list(df['review'].values)

data

['Thanks for an excellent report',
 'Your service is very quick and fast',
 'I am pleased with your service',
 'I did not know i was diabetic until you gave me this report',
 'Service - Little slow, probably because too many people.',
 'The place is not easy to locate',
 'The place is very easy to locate',
 'Not satisfied will take a second opinion',
 'No human contact everything is so robotic here']

In [5]:
data_token = [word_tokenize(x.lower()) for x in data]
clean_data = []

for sent in data_token:
    print([x for x in sent if (x not in stopwords and x not in "-.,")])
    clean_data.append([x for x in sent if (x not in stopwords and x not in "-.,")])

['thanks', 'excellent', 'report']
['service', 'quick', 'fast']
['pleased', 'service']
['know', 'diabetic', 'gave', 'report']
['service', 'little', 'slow', 'probably', 'many', 'people']
['place', 'easy', 'locate']
['place', 'easy', 'locate']
['satisfied', 'take', 'second', 'opinion']
['human', 'contact', 'everything', 'robotic']


In [6]:
clean_data

[['thanks', 'excellent', 'report'],
 ['service', 'quick', 'fast'],
 ['pleased', 'service'],
 ['know', 'diabetic', 'gave', 'report'],
 ['service', 'little', 'slow', 'probably', 'many', 'people'],
 ['place', 'easy', 'locate'],
 ['place', 'easy', 'locate'],
 ['satisfied', 'take', 'second', 'opinion'],
 ['human', 'contact', 'everything', 'robotic']]

In [7]:
vocabs = list(set([val for sublist in clean_data for val in sublist]))

vocal_len = len(vocabs)

vocal_len

26

In [8]:
import numpy as np
one_hot_encode_vector = np.zeros(vocal_len)

one_hot_encode_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
onehot = []
one_hot_encode_vector = []

for words in clean_data:
    one_hot_encode_vector = np.zeros(vocal_len)
    for word in words:
        if word in vocabs:
            indx = vocabs.index(word)
            one_hot_encode_vector[indx] = 1
    
    onehot.append(one_hot_encode_vector)

In [15]:
import pandas as pd

pd.DataFrame(onehot,columns=vocabs).T

0    1    2    3    4    5    6    7    8
robotic     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
pleased     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
slow        0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
thanks      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
place       0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
easy        0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
contact     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
gave        0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
fast        0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
satisfied   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
excellent   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
many        0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
quick       0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
locate      0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
take        0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
people      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
second      0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
know        0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
little      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
opinion     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
report      1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
service     0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0
diabetic    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
probably    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
human       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
everything  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

### Example 02

In [4]:
import pandas as pd

train = [("Thanks for an excellent report", "pos"),
         ("Your service is very quick and fast", "pos"),
        ("I am pleased with your service", "pos"),
        ("I did not know i was diabetic until you gave me this report", "neg"),
        ("Service - Little slow, probably because too many people.", "neg"),
        ("The place is not easy to locate", "neg"),
        ("The place is very easy to locate", "pos"),
        ("Not satisfied will take a second opinion", "neg"),
        ("No human contact everything is so robotic here", "neg")]

df = pd.DataFrame(train,columns=['review','sentiment'])

df.head()


from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stopwords = stopwords.words('english')

data = list(df['review'].values)

data

data_token = [word_tokenize(x.lower()) for x in data]
clean_data = []

for sent in data_token:
    #print([x for x in sent if (x not in stopwords and x not in "-.,")])
    clean_data.append([x for x in sent if (x not in stopwords and x not in "-.,")])

clean_data

[['thanks', 'excellent', 'report'],
 ['service', 'quick', 'fast'],
 ['pleased', 'service'],
 ['know', 'diabetic', 'gave', 'report'],
 ['service', 'little', 'slow', 'probably', 'many', 'people'],
 ['place', 'easy', 'locate'],
 ['place', 'easy', 'locate'],
 ['satisfied', 'take', 'second', 'opinion'],
 ['human', 'contact', 'everything', 'robotic']]

In [6]:
wrds = []

[[wrds.append(w.lower()) for w in x] for x in clean_data]

wrds = set(wrds)

wrds

{'contact',
 'diabetic',
 'easy',
 'everything',
 'excellent',
 'fast',
 'gave',
 'human',
 'know',
 'little',
 'locate',
 'many',
 'opinion',
 'people',
 'place',
 'pleased',
 'probably',
 'quick',
 'report',
 'robotic',
 'satisfied',
 'second',
 'service',
 'slow',
 'take',
 'thanks'}

In [8]:
word_id = {}

for i,w in enumerate(wrds):
    word_id[w] = i

word_id

{'take': 0,
 'quick': 1,
 'satisfied': 2,
 'opinion': 3,
 'robotic': 4,
 'everything': 5,
 'diabetic': 6,
 'place': 7,
 'easy': 8,
 'slow': 9,
 'service': 10,
 'contact': 11,
 'report': 12,
 'thanks': 13,
 'locate': 14,
 'little': 15,
 'excellent': 16,
 'fast': 17,
 'know': 18,
 'pleased': 19,
 'gave': 20,
 'human': 21,
 'probably': 22,
 'people': 23,
 'many': 24,
 'second': 25}

In [13]:
row = len(clean_data)
print("row:",row)

vocab_size = len(word_id)

print("vocab_size=",vocab_size)

import numpy as np
onehot = np.zeros((row,26))

for i in range(len(clean_data)):
    doc = clean_data[i]
    print(doc)
    for j in range(len(doc)):
        id = word_id[(doc[j]).lower()]
        print('word = {0} and id = {1}'.format(doc[j],id))
        
        onehot[i][id] = 1
        
onehot

row: 9
vocab_size= 26
['thanks', 'excellent', 'report']
word = thanks and id = 13
word = excellent and id = 16
word = report and id = 12
['service', 'quick', 'fast']
word = service and id = 10
word = quick and id = 1
word = fast and id = 17
['pleased', 'service']
word = pleased and id = 19
word = service and id = 10
['know', 'diabetic', 'gave', 'report']
word = know and id = 18
word = diabetic and id = 6
word = gave and id = 20
word = report and id = 12
['service', 'little', 'slow', 'probably', 'many', 'people']
word = service and id = 10
word = little and id = 15
word = slow and id = 9
word = probably and id = 22
word = many and id = 24
word = people and id = 23
['place', 'easy', 'locate']
word = place and id = 7
word = easy and id = 8
word = locate and id = 14
['place', 'easy', 'locate']
word = place and id = 7
word = easy and id = 8
word = locate and id = 14
['satisfied', 'take', 'second', 'opinion']
word = satisfied and id = 2
word = take and id = 0
word = second and id = 25
word =

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 1., 

In [17]:
import pandas as pd

pd.DataFrame(onehot,columns=wrds)

take  quick  satisfied  opinion  robotic  everything  diabetic  place  \
0   0.0    0.0        0.0      0.0      0.0         0.0       0.0    0.0   
1   0.0    1.0        0.0      0.0      0.0         0.0       0.0    0.0   
2   0.0    0.0        0.0      0.0      0.0         0.0       0.0    0.0   
3   0.0    0.0        0.0      0.0      0.0         0.0       1.0    0.0   
4   0.0    0.0        0.0      0.0      0.0         0.0       0.0    0.0   
5   0.0    0.0        0.0      0.0      0.0         0.0       0.0    1.0   
6   0.0    0.0        0.0      0.0      0.0         0.0       0.0    1.0   
7   1.0    0.0        1.0      1.0      0.0         0.0       0.0    0.0   
8   0.0    0.0        0.0      0.0      1.0         1.0       0.0    0.0   

   easy  slow  ...  excellent  fast  know  pleased  gave  human  probably  \
0   0.0   0.0  ...        1.0   0.0   0.0      0.0   0.0    0.0       0.0   
1   0.0   0.0  ...        0.0   1.0   0.0      0.0   0.0    0.0       0.0   
2   0.0   0.0  ...        0.0   0.0   0.0      1.0   0.0    0.0       0.0   
3   0.0   0.0  ...        0.0   0.0   1.0      0.0   1.0    0.0       0.0   
4   0.0   1.0  ...        0.0   0.0   0.0      0.0   0.0    0.0       1.0   
5   1.0   0.0  ...        0.0   0.0   0.0      0.0   0.0    0.0       0.0   
6   1.0   0.0  ...        0.0   0.0   0.0      0.0   0.0    0.0       0.0   
7   0.0   0.0  ...        0.0   0.0   0.0      0.0   0.0    0.0       0.0   
8   0.0   0.0  ...        0.0   0.0   0.0      0.0   0.0    1.0       0.0   

   people  many  second  
0     0.0   0.0     0.0  
1     0.0   0.0     0.0  
2     0.0   0.0     0.0  
3     0.0   0.0     0.0  
4     1.0   1.0     0.0  
5     0.0   0.0     0.0  
6     0.0   0.0     0.0  
7     0.0   0.0     1.0  
8     0.0   0.0     0.0  

[9 rows x 26 columns]