In [ ]:
'''
Encoding words is the process of representing each word as a vector

# Multiple Technique to Prepare Input data in NLP

    1. Split Senetence to Words
    2. Unique words in Senetnce
    3. Finding Vocabulary and Vocabulary size
    4. Max length of the words in document
    5. Get Legnth of the Word
    6. Get word indexs in a Sentence
    7. Encode the Text
    8. Finding the Vobabulary,Vocabulary Size and Char to List Conversion
    9. Word Frequency (Word Count)
    10.Word Frequency (Word Count) using collections
    11.Convert Char to Int
    12.List of Words to List of Integer
    13.Sequence of Sentences into List of Words
    14.Sequence of Sentences into List of Words Using List comprehension
    15.Sequence of Sentences to Seqeunce of Integer
    16.Text to Integer Word Encoding
    17.Count the words (Word Frequency)
    18.Find Most Common word
    19.N Gram Bigram and Trigram
    20.N Gram from Sequence List
    21.Label Encoder
    22.Ordinal Encoder
    23.Count Vectorizer
    24.One Hot Encoder for Single Senetence
    25.One Hot Ending for Multiple Sentence
    26.Multi Dimenstional One Hot Encoding
    27.Decode One Hot Encoded Array
    28.Sequence to Matrix (Binary,Count,Frequency)
    29.Bag of words
    30.TFIDF
    32.Padding
    33.Pad Sequence (Pre and Post)
    34.Truncating Sequence (Pre and Post)
    35.Frequency Distribution
    36.Union and Intersection
    37.Generate Input for the RNN
    38.Conversion of Dimention of data : specially for LSTM
    39.Embedding of the Characters in the string : for LSTM
    40.CBOW
    41.Skip Gram
    42.Loading Pretrained Word Embeddings : Glove
    43.Creating word embedding for our Corpus
    44.Word2Vec Using gensim Model
    
    # Pending
        word2id
        id2Word


In [ ]:
'''
Different Functions in Keras for Word Embedding

1. from tensorflow.keras.preprocessing.text import text_to_word_sequence
2. 


In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import tensorflow as tf

In [6]:
# Split Senetence to Words

sentence = "The brown fox is quick and he is jumping over the lazy dog"

words = sentence.split()

print(words)

['The', 'brown', 'fox', 'is', 'quick', 'and', 'he', 'is', 'jumping', 'over', 'the', 'lazy', 'dog']


In [7]:
# Unique words in Senetnce

sentence = "The brown fox is quick and he is jumping over the lazy dog"
print(set(sentence.lower().split()))

{'jumping', 'is', 'the', 'dog', 'and', 'quick', 'he', 'brown', 'over', 'fox', 'lazy'}


In [12]:
# Finding Vocabulary and Vocabulary size

from tensorflow.keras.preprocessing.text import text_to_word_sequence

# define the document
text = "The brown fox is quick and he is jumping over the lazy dog"

# estimate the size of the vocabulary
vocab = set(text_to_word_sequence(text))
vocab_size = len(vocab)

print(vocab)

print(vocab_size)
# integer encode the document

{'jumping', 'is', 'the', 'dog', 'and', 'quick', 'he', 'brown', 'over', 'fox', 'lazy'}
11


In [3]:
### Hash Vectroizer

from sklearn.feature_extraction.text import HashingVectorizer
# list of text documents
text = ["The quick brown fox jumped over the lazy dog."]
# create the transform
vectorizer = HashingVectorizer(n_features=20)
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(1, 20)
[[ 0.          0.          0.          0.          0.          0.33333333
   0.         -0.33333333  0.33333333  0.          0.          0.33333333
   0.          0.          0.         -0.33333333  0.          0.
  -0.66666667  0.        ]]


In [6]:
### Hash Encoding with hashing_trick_Keras

from tensorflow.keras.preprocessing.text import hashing_trick
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# define the document
text = 'The quick brown fox jumped over the lazy dog.'

# estimate the size of the vocabulary
words = set(text_to_word_sequence(text))
vocab_size = len(words)

print(vocab_size)
# integer encode the document

result = hashing_trick(text, round(vocab_size * 1.3), hash_function='md5')
print(result)

8
[6, 4, 1, 2, 7, 5, 6, 2, 6]


In [15]:
# Max length of the words in document

# Split Senetence to Words

sentence = "The brown fox is quick and he is jumping over the lazy dog"

words = sentence.split()

print(words)

np.max([len(x) for x in words])

['The', 'brown', 'fox', 'is', 'quick', 'and', 'he', 'is', 'jumping', 'over', 'the', 'lazy', 'dog']


7

In [16]:
# Get Legnth of the Word

import string

all_letters = string.ascii_letters + ".,;''"

print("all_letters = {0}".format(all_letters))

n_letters = len(all_letters)

print("Length of letters = {0}".format(n_letters))

all_letters = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.,;''
Length of letters = 57


In [17]:
# Get word indexs in a Sentence

sentence = "The brown fox is quick and he is jumping over the lazy dog"

corpus = sentence.split()

uniq_text = set(corpus)
text_to_int = {}

for i, c in enumerate (uniq_text):
    text_to_int.update({c: i})
    
print(text_to_int)

{'jumping': 0, 'is': 1, 'the': 2, 'The': 3, 'dog': 4, 'and': 5, 'quick': 6, 'he': 7, 'brown': 8, 'over': 9, 'fox': 10, 'lazy': 11}


In [19]:
# Encode the Text

text = ['Hi',"How","are","you","Hi","coming"]

character_list = list(set(text))   # get all of the unique letters in our text variable
vocabulary_size = len(character_list)   # count the number of unique elements

# create a dictionary mapping each unique char to a number
character_dictionary = {char:e for e, char in enumerate(character_list)}  
encoded_chars = [character_dictionary[char] for char in text] #integer representation of our vocabulary 

encoded_chars

[1, 0, 3, 4, 1, 2]

In [3]:
# Text to Integer Sequence 

from tensorflow.keras.preprocessing.text import Tokenizer

t = Tokenizer()

fit_text = ["The earth is an awesome place live"]

t.fit_on_texts(fit_text)

test_text1 = "The earth is an great place live"
test_text2 = "The is my program"

sequences = t.texts_to_sequences([test_text1, test_text2])

print(sequences)

print('word_index : ',t.word_index)

print(list(t.word_index.keys()))

[[1, 2, 3, 4, 6, 7], [1, 3]]
word_index :  {'the': 1, 'earth': 2, 'is': 3, 'an': 4, 'awesome': 5, 'place': 6, 'live': 7}
['the', 'earth', 'is', 'an', 'awesome', 'place', 'live']


In [20]:
# Finding the Vobabulary,Vocabulary Size and Char to List Conversaion

data = ['hi','how','are','you','merry','santhosh']

chars = []

char_id = dict()

for i in range(len(data)):
    for j in range(len(data[i])):
        chars.append(data[i][j])
        
print("unique Charatcers(Vocabulary) in the document:{0}".format(set(chars)))
print("Size of the Vocabulary={0}".format(len(set(chars))))


# Char to integer 
for (i,val) in enumerate(chars):
    char_id[val] = i
    
char_id

unique Charatcers(Vocabulary) in the document:{'y', 'w', 'u', 'm', 'a', 'h', 'i', 'r', 'e', 'o', 's', 'n', 't'}
Size of the Vocabulary=13


{'h': 23,
 'i': 1,
 'o': 21,
 'w': 4,
 'a': 17,
 'r': 14,
 'e': 12,
 'y': 15,
 'u': 10,
 'm': 11,
 's': 22,
 'n': 18,
 't': 19}

In [21]:
# Word Frequency (Word Count)

word_freq = {}

sentence = "The brown fox is quick and he is jumping over the lazy dog"

for tok in sentence.split():
    if tok in word_freq:
        word_freq[tok] +=1
    else:
        word_freq[tok] = 1

print(word_freq)

{'The': 1, 'brown': 1, 'fox': 1, 'is': 2, 'quick': 1, 'and': 1, 'he': 1, 'jumping': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1}


In [22]:
# Word Frequency (Word Count) using collections

import collections

counter = collections.Counter(sentence.split())

print(counter)

print("\n Most common:")

# Find Most Common word
counter.most_common(8)

Counter({'is': 2, 'The': 1, 'brown': 1, 'fox': 1, 'quick': 1, 'and': 1, 'he': 1, 'jumping': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1})

 Most common:


[('is', 2),
 ('The', 1),
 ('brown', 1),
 ('fox', 1),
 ('quick', 1),
 ('and', 1),
 ('he', 1),
 ('jumping', 1)]

In [45]:
# Convert Char to Int

text = ['hey how are you','good i am fine','have a nice day']

# Join all the sentences together and extract the unique characters from the combined sentences
chars = set(''.join(text))

# Creating a dictionary that maps integers to the characters
int2char = dict(enumerate(chars))

# Creating another dictionary that maps characters to integers
char2int = {char: ind for ind, char in int2char.items()}

char2int

{'y': 0,
 'w': 1,
 'u': 2,
 'm': 3,
 'a': 4,
 'h': 5,
 'i': 6,
 ' ': 7,
 'c': 8,
 'r': 9,
 'f': 10,
 'v': 11,
 'e': 12,
 'o': 13,
 'd': 14,
 'n': 15,
 'g': 16}

### word2id,id2word and wids

In [11]:
# List of Words to List of Integer

from tensorflow.keras.preprocessing import text
from tensorflow.keras.preprocessing import sequence

sdff = [['The', 'King', 'James', 'Bible'],
        ['The', 'Old', 'Testament', 'of', 'the', 'King', 'James', 'Bible'],
        ['The', 'First', 'Book', 'of', 'Moses', ':', 'Called', 'Genesis']]

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(sdff)
word2id = tokenizer.word_index

word2id.items()

id2word = {v:k for k, v in word2id.items()}

wids = [[word2id[y.lower()] for y in x] for x in sdff]


vocab_size = len(word2id)

print('Vocabulary Sample:', list(word2id.items()))

print("\n vocab_size ={0}".format(vocab_size))

print("\nwids:\n",wids)
print("\nword2id: \n",word2id)
print("\nid2Word: \n",id2word)

Vocabulary Sample: [('the', 1), ('king', 2), ('james', 3), ('bible', 4), ('of', 5), ('old', 6), ('testament', 7), ('first', 8), ('book', 9), ('moses', 10), (':', 11), ('called', 12), ('genesis', 13)]

 vocab_size =13

wids:
 [[1, 2, 3, 4], [1, 6, 7, 5, 1, 2, 3, 4], [1, 8, 9, 5, 10, 11, 12, 13]]

word2id: 
 {'the': 1, 'king': 2, 'james': 3, 'bible': 4, 'of': 5, 'old': 6, 'testament': 7, 'first': 8, 'book': 9, 'moses': 10, ':': 11, 'called': 12, 'genesis': 13}

id2Word: 
 {1: 'the', 2: 'king', 3: 'james', 4: 'bible', 5: 'of', 6: 'old', 7: 'testament', 8: 'first', 9: 'book', 10: 'moses', 11: ':', 12: 'called', 13: 'genesis'}


In [9]:
# Text to Integer

list1 = ['Located', 'on', 'the', 'southern', 'tip', 'of', 'Lake', 'Union,', 'the', 'Hilton']

text_int ={}

for i,j in enumerate(list1):
    text_int.update({j:(i+1)})
    
text_int

{'Located': 1,
 'on': 2,
 'the': 9,
 'southern': 4,
 'tip': 5,
 'of': 6,
 'Lake': 7,
 'Union,': 8,
 'Hilton': 10}

In [4]:
# Sequence of Sentences into List of Words

from tensorflow.keras.preprocessing.text import text_to_word_sequence

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

[[w for w in text_to_word_sequence(doc)] for doc in norm_bible]

[['king', 'james', 'bible'],
 ['old', 'testament', 'king', 'james', 'bible'],
 ['first', 'book', 'moses', 'called', 'genesis'],
 ['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters'],
 ['god', 'said', 'let', 'light', 'light'],
 ['god', 'saw', 'light', 'good', 'god', 'divided', 'light', 'darkness'],
 ['god', 'called', 'light', 'day', 'darkness', 'called', 'night'],
 ['evening', 'morning', 'first', 'day']]

In [5]:
# Sequence of Sentences into List of Words Using List comprehension

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

[[word for word in document.lower().split()] for document in norm_bible]

[['king', 'james', 'bible'],
 ['old', 'testament', 'king', 'james', 'bible'],
 ['first', 'book', 'moses', 'called', 'genesis'],
 ['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters'],
 ['god', 'said', 'let', 'light', 'light'],
 ['god', 'saw', 'light', 'good', 'god', 'divided', 'light', 'darkness'],
 ['god', 'called', 'light', 'day', 'darkness', 'called', 'night'],
 ['evening', 'morning', 'first', 'day']]

In [32]:
# Sequence of Sentences to Seqeunce of Integer

from tensorflow.keras.preprocessing import text

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[[5, 6, 7],
 [13, 14, 5, 6, 7],
 [8, 15, 16, 3, 17],
 [18, 1, 19, 20, 9],
 [9, 21, 22, 23, 4, 10, 11, 24],
 [25, 1, 26, 10, 11, 27],
 [1, 28, 29, 2, 2],
 [1, 30, 2, 31, 1, 32, 2, 4],
 [1, 3, 2, 12, 4, 3, 33],
 [34, 35, 8, 12]]

In [24]:
# Text to Integer Word Encoding

text ='''Located on the southern tip of Lake Union, the Hilton Garden Inn Seattle Downtown hotel 
        is perfectly located for business and leisure. \nThe neighborhood is home to numerous major 
        international companies including Amazon, Google and the Bill & Melinda Gates Foundation. 
        A wealth of eclectic restaurants and bars make this area of Seattle one of the most sought out 
        by locals and visitors. Our proximity to Lake Union allows visitors to take in some of the Pacific
        Northwest's majestic scenery and enjoy outdoor activities like kayaking and sailing. over 2,000 sq. ft. 
        of versatile space and a complimentary business center. State-of-the-art A/V technology and our helpful 
        staff will guarantee your conference, cocktail reception or wedding is a success. Refresh in the sparkling 
        saltwater pool, or energize with the latest equipment in the 24-hour fitness center. Tastefully decorated 
        and flooded with natural light, our guest rooms and suites offer everything you need to relax and stay productive. 
        Unwind in the bar, and enjoy American cuisine for breakfast, lunch and dinner in our restaurant. The 24-hour Pavilion
        Pantry? stocks a variety of snacks, drinks and sundries'''


corpus = text.split()

uniq_text = set(corpus)

text_to_int = {}

for i, c in enumerate (uniq_text):
    text_to_int.update({c: i})
    
text_to_int

{'Pavilion': 0,
 'the': 1,
 'energize': 2,
 'Gates': 3,
 'complimentary': 4,
 'cocktail': 5,
 '24-hour': 6,
 'Hilton': 7,
 'perfectly': 8,
 'over': 9,
 'space': 10,
 'center.': 11,
 'one': 12,
 'dinner': 13,
 'rooms': 14,
 'conference,': 15,
 'staff': 16,
 'to': 17,
 'guarantee': 18,
 'your': 19,
 'restaurants': 20,
 'Refresh': 21,
 'visitors.': 22,
 'wedding': 23,
 'breakfast,': 24,
 'leisure.': 25,
 '2,000': 26,
 'Bill': 27,
 'with': 28,
 'Unwind': 29,
 'Union,': 30,
 'Garden': 31,
 'Union': 32,
 'our': 33,
 'bar,': 34,
 'sparkling': 35,
 'neighborhood': 36,
 'sq.': 37,
 'restaurant.': 38,
 'A/V': 39,
 'home': 40,
 'success.': 41,
 'relax': 42,
 'flooded': 43,
 'located': 44,
 'stocks': 45,
 'State-of-the-art': 46,
 'Pantry?': 47,
 'A': 48,
 'guest': 49,
 'a': 50,
 'decorated': 51,
 'need': 52,
 'natural': 53,
 'companies': 54,
 'reception': 55,
 'visitors': 56,
 'Our': 57,
 'Tastefully': 58,
 'latest': 59,
 'hotel': 60,
 'productive.': 61,
 'Downtown': 62,
 'wealth': 63,
 'lunch': 6

In [25]:
# Count the words (Word Frequency)

import collections

counter = collections.Counter(text.split())

counter

Counter({'Located': 1,
         'on': 1,
         'the': 9,
         'southern': 1,
         'tip': 1,
         'of': 7,
         'Lake': 2,
         'Union,': 1,
         'Hilton': 1,
         'Garden': 1,
         'Inn': 1,
         'Seattle': 2,
         'Downtown': 1,
         'hotel': 1,
         'is': 3,
         'perfectly': 1,
         'located': 1,
         'for': 2,
         'business': 2,
         'and': 14,
         'leisure.': 1,
         'The': 2,
         'neighborhood': 1,
         'home': 1,
         'to': 4,
         'numerous': 1,
         'major': 1,
         'international': 1,
         'companies': 1,
         'including': 1,
         'Amazon,': 1,
         'Google': 1,
         'Bill': 1,
         '&': 1,
         'Melinda': 1,
         'Gates': 1,
         'Foundation.': 1,
         'A': 1,
         'wealth': 1,
         'eclectic': 1,
         'restaurants': 1,
         'bars': 1,
         'make': 1,
         'this': 1,
         'area': 1,
         'one': 1,
  

In [26]:
# Find Most Common word
counter.most_common(8)

[('and', 14),
 ('the', 9),
 ('of', 7),
 ('in', 5),
 ('to', 4),
 ('is', 3),
 ('a', 3),
 ('our', 3)]

In [28]:
# N Gram (n =2): Bigram

sentence = "The brown fox is quick and he is jumping over the lazy dog"

words =sentence.split()

n = 2
output= []
for i in range(len(words) - n+1):
    output.append(words[i:i+n])
    
output

[['The', 'brown'],
 ['brown', 'fox'],
 ['fox', 'is'],
 ['is', 'quick'],
 ['quick', 'and'],
 ['and', 'he'],
 ['he', 'is'],
 ['is', 'jumping'],
 ['jumping', 'over'],
 ['over', 'the'],
 ['the', 'lazy'],
 ['lazy', 'dog']]

In [29]:
# N Gram (n =3): Trigram

words =sentence.split()

sentence = "The brown fox is quick and he is jumping over the lazy dog"

n = 3
output= []
for i in range(len(words) - n+1):
    output.append(words[i:i+n])
    
output

[['The', 'brown', 'fox'],
 ['brown', 'fox', 'is'],
 ['fox', 'is', 'quick'],
 ['is', 'quick', 'and'],
 ['quick', 'and', 'he'],
 ['and', 'he', 'is'],
 ['he', 'is', 'jumping'],
 ['is', 'jumping', 'over'],
 ['jumping', 'over', 'the'],
 ['over', 'the', 'lazy'],
 ['the', 'lazy', 'dog']]

### Padding Manual

In [2]:
# Example 2:

import numpy as np

data = [['Thanks', 'for', 'an', 'excellent', 'report'],
        ['Your', 'service', 'is', 'very', 'quick', 'and', 'fast'],
        ['I', 'am', 'pleased', 'with', 'your', 'service']]

wrds = []

[[wrds.append(w.lower()) for w in x] for x in data]

wrds = set(wrds)

print(wrds,"\n")

word_id = {}

for i,w in enumerate(wrds,1):
    word_id[w] = i
    
print(word_id,"\n")

row = len(data)

column = np.max([len(x) for x in data])

print("row={0} and column={1}".format(row,column))

seq_embedding = np.zeros((row,column))

print("seq_embedding = \n {0}".format(seq_embedding))

print("\n")

for i in range(len(data)):
    doc = data[i]
    for j in range(len(doc)):
        id = word_id[(doc[j]).lower()]
        seq_embedding[i][j] = id
        
print(seq_embedding)

{'for', 'quick', 'very', 'an', 'thanks', 'pleased', 'am', 'fast', 'your', 'i', 'is', 'and', 'service', 'report', 'excellent', 'with'} 

{'for': 1, 'quick': 2, 'very': 3, 'an': 4, 'thanks': 5, 'pleased': 6, 'am': 7, 'fast': 8, 'your': 9, 'i': 10, 'is': 11, 'and': 12, 'service': 13, 'report': 14, 'excellent': 15, 'with': 16} 

row=3 and column=7
seq_embedding = 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[ 5.  1.  4. 15. 14.  0.  0.]
 [ 9. 13. 11.  3.  2. 12.  8.]
 [10.  7.  6. 16.  9. 13.  0.]]


In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# N Gram from Sequence List

lst = [24,34,1,9,56,76,90,11,67,54,14]

data = []

for i in range(0,len(lst)):
    print(lst[:i+1])
    data.append(lst[:i+1])

# Padding
pad_sequences(data,padding='post')

[24]
[24, 34]
[24, 34, 1]
[24, 34, 1, 9]
[24, 34, 1, 9, 56]
[24, 34, 1, 9, 56, 76]
[24, 34, 1, 9, 56, 76, 90]
[24, 34, 1, 9, 56, 76, 90, 11]
[24, 34, 1, 9, 56, 76, 90, 11, 67]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54, 14]


array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54, 14]])

In [33]:
# LabelEncoder

from sklearn.preprocessing import LabelEncoder

doc =  ['S','C','Q','S','C','Q','S','C','Q','Q','C','Q','C','Q','Q']

label_encoder = LabelEncoder()

label_encoder.fit(['S','C','Q'])

label_encoder.transform(doc)

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1])

In [34]:
# OrdinalEncoder converts each string value to a whole number. 
# The first unique value in your column becomes 1, the second becomes 2, the third becomes 3, and so on.

from sklearn.preprocessing import OrdinalEncoder
import numpy as np

doc =  [['S'],['C'],['Q'],['S'],['C'],['Q'],['S'],['C'],['Q'],['Q'],['C'],['Q'],['C'],['Q'],['Q']]

encoder = OrdinalEncoder()

encoder.fit_transform(doc)

array([[2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [35]:
# OrdinalEncoder

import numpy as np

X = np.array([["good", "london"],
             ["good", "tokyo"],
             ["bad", "paris"],
             ["average", "so so"],
             ["good", "tokyo"]])

encoder = OrdinalEncoder()
encoder.fit_transform(X)

array([[2., 0.],
       [2., 3.],
       [1., 1.],
       [0., 2.],
       [2., 3.]])

In [36]:
# Count Vectorizer

from sklearn.feature_extraction.text import CountVectorizer

docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining and the weather is sweet'])

count = CountVectorizer()
bag = count.fit_transform(docs)

bag.toarray()

# Index

# and = 0
# is =1
# shining = 2
# sun =3
# sweet =4
# the =5
# wether =6

array([[0, 1, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 1],
       [1, 2, 1, 1, 1, 2, 1]], dtype=int64)

                                            Document Category
0                     The sky is blue and beautiful.  weather
1                  Love this blue and beautiful sky!  weather
2       The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, e...     food
4        I love green eggs, ham, sausages and bacon!     food
5   The brown fox is quick and the blue dog is lazy!  animals
6  The sky is very blue and the sky is very beaut...  weather
7        The dog is lazy but the brown fox is quick!  animals


array(['sky blue beautiful', 'love blue beautiful sky',
       'quick brown fox jumps lazy dog',
       'kings breakfast sausages ham bacon eggs toast beans',
       'love green eggs ham sausages bacon',
       'brown fox quick blue dog lazy', 'sky blue sky beautiful today',
       'dog lazy brown fox quick'], dtype='<U51')

In [37]:
# Binary One Hot Encoder for Single Senetence

from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.preprocessing.text import Tokenizer

# Bag of Word

# One Hot Encoding

doc = "Can I eat the Pizza".lower().split()

t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(doc)

# integer encode documents
encoded_docs = t.texts_to_matrix(doc, mode='count')

encoded_docs

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
# One Hot Ending for Multiple Sentence

from tensorflow.keras.preprocessing.text import Tokenizer

doc = [['can', 'i', 'eat', 'the', 'pizza'],['can', 'i', 'eat', 'the', 'pizza']]

t = Tokenizer()

# fit the tokenizer on the documents
t.fit_on_texts(doc)

# integer encode documents
encoded_docs = t.texts_to_matrix(doc, mode='count')

encoded_docs

array([[0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.]])

In [39]:
# Multi Dimenstional One Hot Encoding

from tensorflow.keras.utils import to_categorical

x = [[1,2,3,4,5],
     [1,4,8,4,4],
     [1,2,3,3,5]]

y = to_categorical(x, num_classes=10)

y

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]], dtype=float32)

In [40]:
# Decode One Hot Encoded Array

from numpy import argmax

from tensorflow.keras.utils import to_categorical

x = [[1,2,3,4,5],
     [1,4,8,4,4],
     [1,2,3,3,5]]

print("input Array")
print(x)

print("\n")

one_hot_arry = to_categorical(x, num_classes=10)

print("One Hot Encoding of input:")
print(one_hot_arry)

print("\n")
print("Decoded output of One Hot Encoding")
decoded_one_hot = [[argmax(aa) for aa in array] for array in one_hot_arry]

print(decoded_one_hot)

input Array
[[1, 2, 3, 4, 5], [1, 4, 8, 4, 4], [1, 2, 3, 3, 5]]


One Hot Encoding of input:
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]]


Decoded output of One Hot Encoding
[[1, 2, 3, 4, 5], [1, 4, 8, 4, 4], [1, 2, 3, 3, 5]]


In [41]:
# Sequence to Matrix (mode = binary and num_words = 10)

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='binary')

x_train

array([[0., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0.]])

In [42]:
# Sequences to Matrix (mode = count and num_words = 10)
tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='count')

x_train

array([[0., 2., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0.]])

In [43]:
# Sequences to Matrix (mode = freq and num_words = 10)
tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='freq')

import pandas as pd

pd.DataFrame(x_train)

0    1    2    3    4    5         6         7         8    9
0  0.0  0.4  0.2  0.2  0.2  0.0  0.000000  0.000000  0.000000  0.0
1  0.0  0.0  0.0  0.0  0.5  0.5  0.000000  0.000000  0.000000  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.333333  0.333333  0.333333  0.0

In [44]:
# Bag of words

import numpy as np
docs = ["It was the best of time","It was the worst of times","It was the age of wisdom","It was the age of foolishness"]

row = len(docs)

words = []
for i in range(len(docs)):
    spli_sentenc = docs[i].split()
    for j in range(len(spli_sentenc)):
        words.append(spli_sentenc[j])
        
vocab = set(words)
print("Vocabulary={0}".format(vocab))
print("Vicab_size = {0}".format(vocab_size))
vocab_size = (len(vocab))
column = vocab_size

tensor = np.zeros((row,column))

print(tensor)

words_id = {}

for i,wrd in enumerate(vocab):
    words_id[wrd] = i
    
print("Word to Integer : = {0}".format(words_id))
    
for i in range(len(docs)):
    words = docs[i].split()
    for j in range(len(words)):
        tensor[i][words_id[words[j]]] = 1
        
print(tensor)

import pandas as pd

pd.DataFrame(tensor,columns=vocab)

Vocabulary={'worst', 'wisdom', 'the', 'time', 'best', 'age', 'It', 'times', 'foolishness', 'of', 'was'}
Vicab_size = 11
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Word to Integer : = {'worst': 0, 'wisdom': 1, 'the': 2, 'time': 3, 'best': 4, 'age': 5, 'It': 6, 'times': 7, 'foolishness': 8, 'of': 9, 'was': 10}
[[0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1.]]


worst  wisdom  the  time  best  age   It  times  foolishness   of  was
0    0.0     0.0  1.0   1.0   1.0  0.0  1.0    0.0          0.0  1.0  1.0
1    1.0     0.0  1.0   0.0   0.0  0.0  1.0    1.0          0.0  1.0  1.0
2    0.0     1.0  1.0   0.0   0.0  1.0  1.0    0.0          0.0  1.0  1.0
3    0.0     0.0  1.0   0.0   0.0  1.0  1.0    0.0          1.0  1.0  1.0

In [50]:
# TFIDF

# tf-idf = tf(i,d) * idf(t,d)

# td(i,d) = term frequency

# idf(t,d) = 	log(n/1+df(t,d)) :  inverse document frequency  df(t,d) : no. of documents d that contain the term t

import pandas as pd

corpus = ["Data Science is an overlap between Arts and Science",
          "Generally,Arts graduates are right-brained and Science graduates are left-brained",
          "Excelling in both Arts and Science at a time becomes difficult",
          "Natural Language Processing is a part of Data Science"]

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_model = TfidfVectorizer()
features = tfidf_model.fit_transform(corpus)
df = pd.DataFrame(features.todense(),columns= sorted(tfidf_model.vocabulary_))

df

an       and       are      arts        at   becomes   between  \
0  0.403328  0.257439  0.000000  0.257439  0.000000  0.000000  0.403328   
1  0.000000  0.159139  0.498644  0.159139  0.000000  0.000000  0.000000   
2  0.000000  0.224449  0.000000  0.224449  0.351643  0.351643  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       both   brained      data  ...  language      left   natural        of  \
0  0.000000  0.000000  0.317989  ...  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.498644  0.000000  ...  0.000000  0.249322  0.000000  0.000000   
2  0.351643  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.308872  ...  0.391765  0.000000  0.391765  0.391765   

    overlap      part  processing     right   science      time  
0  0.403328  0.000000    0.000000  0.000000  0.420947  0.000000  
1  0.000000  0.000000    0.000000  0.249322  0.130107  0.000000  
2  0.000000  0.000000    0.000000  0.000000  0.183502  0.351643  
3  0.000000  0.391765    0.391765  0.000000  0.204439  0.000000  

[4 rows x 26 columns]

In [13]:
# building a corpus of documents

import numpy as np
import pandas as pd
import nltk
import re


corpus = ['The sky is blue and beautiful.',
          'Love this blue and beautiful sky!',
          'The quick brown fox jumps over the lazy dog.',
          "A king's breakfast has sausages, ham, bacon, eggs, toast and beans",
          'I love green eggs, ham, sausages and bacon!',
          'The brown fox is quick and the blue dog is lazy!',
          'The sky is very blue and the sky is very beautiful today',
          'The dog is lazy but the brown fox is quick!'
          ]
labels = ['weather', 'weather', 'animals', 'food', 'food', 'animals', 'weather', 'animals']

corpus = np.array(corpus)
corpus_df = pd.DataFrame({'Document': corpus, 'Category': labels})
corpus_df = corpus_df[['Document', 'Category']]
print(corpus_df)


wpt = nltk.WordPunctTokenizer()
stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    # lowercase and remove special characters\whitespace
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # tokenize document
    tokens = wpt.tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

normalize_corpus = np.vectorize(normalize_document)

norm_corpus = normalize_corpus(corpus)
norm_corpus

                                            Document Category
0                     The sky is blue and beautiful.  weather
1                  Love this blue and beautiful sky!  weather
2       The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, e...     food
4        I love green eggs, ham, sausages and bacon!     food
5   The brown fox is quick and the blue dog is lazy!  animals
6  The sky is very blue and the sky is very beaut...  weather
7        The dog is lazy but the brown fox is quick!  animals


array(['sky blue beautiful', 'love blue beautiful sky',
       'quick brown fox jumps lazy dog',
       'kings breakfast sausages ham bacon eggs toast beans',
       'love green eggs ham sausages bacon',
       'brown fox quick blue dog lazy', 'sky blue sky beautiful today',
       'dog lazy brown fox quick'], dtype='<U51')

In [14]:
# Bag of Words model

from sklearn.feature_extraction.text import CountVectorizer

# get bag of words features in sparse format
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(norm_corpus)
cv_matrix

# view non-zero feature positions in the sparse matrix
print(cv_matrix)

  (0, 17)	1
  (0, 3)	1
  (0, 2)	1
  (1, 17)	1
  (1, 3)	1
  (1, 2)	1
  (1, 14)	1
  (2, 15)	1
  (2, 5)	1
  (2, 8)	1
  (2, 11)	1
  (2, 13)	1
  (2, 6)	1
  (3, 12)	1
  (3, 4)	1
  (3, 16)	1
  (3, 10)	1
  (3, 0)	1
  (3, 7)	1
  (3, 18)	1
  (3, 1)	1
  (4, 14)	1
  (4, 16)	1
  (4, 10)	1
  (4, 0)	1
  (4, 7)	1
  (4, 9)	1
  (5, 3)	1
  (5, 15)	1
  (5, 5)	1
  (5, 8)	1
  (5, 13)	1
  (5, 6)	1
  (6, 17)	2
  (6, 3)	1
  (6, 2)	1
  (6, 19)	1
  (7, 15)	1
  (7, 5)	1
  (7, 8)	1
  (7, 13)	1
  (7, 6)	1


In [15]:
# view dense representation

# warning might give a memory error if data is too big
cv_matrix = cv_matrix.toarray()
cv_matrix

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]],
      dtype=int64)

In [16]:
# One Hot Encoding

# get all unique words in the corpus
vocab = cv.get_feature_names()

# show document feature vectors
pd.DataFrame(cv_matrix, columns=vocab)


bacon  beans  beautiful  blue  breakfast  brown  dog  eggs  fox  green  \
0      0      0          1     1          0      0    0     0    0      0   
1      0      0          1     1          0      0    0     0    0      0   
2      0      0          0     0          0      1    1     0    1      0   
3      1      1          0     0          1      0    0     1    0      0   
4      1      0          0     0          0      0    0     1    0      1   
5      0      0          0     1          0      1    1     0    1      0   
6      0      0          1     1          0      0    0     0    0      0   
7      0      0          0     0          0      1    1     0    1      0   

   ham  jumps  kings  lazy  love  quick  sausages  sky  toast  today  
0    0      0      0     0     0      0         0    1      0      0  
1    0      0      0     0     1      0         0    1      0      0  
2    0      1      0     1     0      1         0    0      0      0  
3    1      0      1     0     0      0         1    0      1      0  
4    1      0      0     0     1      0         1    0      0      0  
5    0      0      0     1     0      1         0    0      0      0  
6    0      0      0     0     0      0         0    2      0      1  
7    0      0      0     1     0      1         0    0      0      0

In [17]:
# BAG OF N-GRAMS MODEL

# you can set the n-gram range to 1,2 to get unigrams as well as bigrams
bv = CountVectorizer(ngram_range=(2,2))

bv_matrix = bv.fit_transform(norm_corpus)
bv_matrix = bv_matrix.toarray()

vocab = bv.get_feature_names()
pd.DataFrame(bv_matrix, columns=vocab)

bacon eggs  beautiful sky  beautiful today  blue beautiful  blue dog  \
0           0              0                0               1         0   
1           0              1                0               1         0   
2           0              0                0               0         0   
3           1              0                0               0         0   
4           0              0                0               0         0   
5           0              0                0               0         1   
6           0              0                1               0         0   
7           0              0                0               0         0   

   blue sky  breakfast sausages  brown fox  dog lazy  eggs ham  ...  lazy dog  \
0         0                   0          0         0         0  ...         0   
1         0                   0          0         0         0  ...         0   
2         0                   0          1         0         0  ...         1   
3         0                   1          0         0         0  ...         0   
4         0                   0          0         0         1  ...         0   
5         0                   0          1         1         0  ...         0   
6         1                   0          0         0         0  ...         0   
7         0                   0          1         1         0  ...         0   

   love blue  love green  quick blue  quick brown  sausages bacon  \
0          0           0           0            0               0   
1          1           0           0            0               0   
2          0           0           0            1               0   
3          0           0           0            0               0   
4          0           1           0            0               1   
5          0           0           1            0               0   
6          0           0           0            0               0   
7          0           0           0            0               0   

   sausages ham  sky beautiful  sky blue  toast beans  
0             0              0         1            0  
1             0              0         0            0  
2             0              0         0            0  
3             1              0         0            1  
4             0              0         0            0  
5             0              0         0            0  
6             0              1         1            0  
7             0              0         0            0  

[8 rows x 29 columns]

In [18]:
# TF-IDf
from sklearn.feature_extraction.text import TfidfTransformer

tt = TfidfTransformer(norm='l2', use_idf=True)
tt_matrix = tt.fit_transform(cv_matrix)
tt_matrix = tt_matrix.toarray()
vocab = cv.get_feature_names()
pd.DataFrame(np.round(tt_matrix, 2), columns=vocab)

bacon  beans  beautiful  blue  breakfast  brown   dog  eggs   fox  green  \
0   0.00   0.00       0.60  0.53       0.00   0.00  0.00  0.00  0.00   0.00   
1   0.00   0.00       0.49  0.43       0.00   0.00  0.00  0.00  0.00   0.00   
2   0.00   0.00       0.00  0.00       0.00   0.38  0.38  0.00  0.38   0.00   
3   0.32   0.38       0.00  0.00       0.38   0.00  0.00  0.32  0.00   0.00   
4   0.39   0.00       0.00  0.00       0.00   0.00  0.00  0.39  0.00   0.47   
5   0.00   0.00       0.00  0.37       0.00   0.42  0.42  0.00  0.42   0.00   
6   0.00   0.00       0.36  0.32       0.00   0.00  0.00  0.00  0.00   0.00   
7   0.00   0.00       0.00  0.00       0.00   0.45  0.45  0.00  0.45   0.00   

    ham  jumps  kings  lazy  love  quick  sausages   sky  toast  today  
0  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.60   0.00    0.0  
1  0.00   0.00   0.00  0.00  0.57   0.00      0.00  0.49   0.00    0.0  
2  0.00   0.53   0.00  0.38  0.00   0.38      0.00  0.00   0.00    0.0  
3  0.32   0.00   0.38  0.00  0.00   0.00      0.32  0.00   0.38    0.0  
4  0.39   0.00   0.00  0.00  0.39   0.00      0.39  0.00   0.00    0.0  
5  0.00   0.00   0.00  0.42  0.00   0.42      0.00  0.00   0.00    0.0  
6  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.72   0.00    0.5  
7  0.00   0.00   0.00  0.45  0.00   0.45      0.00  0.00   0.00    0.0

In [19]:
# Using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(min_df=0., max_df=1., norm="l2",use_idf=True, smooth_idf=True)
tv_matrix = tv.fit_transform(norm_corpus)
tv_matrix = tv_matrix.toarray()
vocab = tv.get_feature_names()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

bacon  beans  beautiful  blue  breakfast  brown   dog  eggs   fox  green  \
0   0.00   0.00       0.60  0.53       0.00   0.00  0.00  0.00  0.00   0.00   
1   0.00   0.00       0.49  0.43       0.00   0.00  0.00  0.00  0.00   0.00   
2   0.00   0.00       0.00  0.00       0.00   0.38  0.38  0.00  0.38   0.00   
3   0.32   0.38       0.00  0.00       0.38   0.00  0.00  0.32  0.00   0.00   
4   0.39   0.00       0.00  0.00       0.00   0.00  0.00  0.39  0.00   0.47   
5   0.00   0.00       0.00  0.37       0.00   0.42  0.42  0.00  0.42   0.00   
6   0.00   0.00       0.36  0.32       0.00   0.00  0.00  0.00  0.00   0.00   
7   0.00   0.00       0.00  0.00       0.00   0.45  0.45  0.00  0.45   0.00   

    ham  jumps  kings  lazy  love  quick  sausages   sky  toast  today  
0  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.60   0.00    0.0  
1  0.00   0.00   0.00  0.00  0.57   0.00      0.00  0.49   0.00    0.0  
2  0.00   0.53   0.00  0.38  0.00   0.38      0.00  0.00   0.00    0.0  
3  0.32   0.00   0.38  0.00  0.00   0.00      0.32  0.00   0.38    0.0  
4  0.39   0.00   0.00  0.00  0.39   0.00      0.39  0.00   0.00    0.0  
5  0.00   0.00   0.00  0.42  0.00   0.42      0.00  0.00   0.00    0.0  
6  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.72   0.00    0.5  
7  0.00   0.00   0.00  0.45  0.00   0.45      0.00  0.00   0.00    0.0

In [51]:
# Padding

raw_inputs = [[83, 91, 1, 645, 1253, 927],[73, 8, 3215, 55, 927],[711, 632, 71]]

vocab_size = np.max([len(x) for x in raw_inputs])

row = len(raw_inputs)
column = vocab_size

tensor = np.zeros((row,column),dtype=np.int32)

for i in range(len(raw_inputs)):
    for j in range(len(raw_inputs[i])):
        tensor[i][j] = raw_inputs[i][j]
        
print(tensor)

[[  83   91    1  645 1253  927]
 [  73    8 3215   55  927    0]
 [ 711  632   71    0    0    0]]


In [52]:
# Padding
# pad_sequences is used to ensure that all sequences in a list have the same length. 

from tensorflow.keras.preprocessing.sequence import pad_sequences

raw_inputs = [
              [83, 91, 1, 645, 1253, 927],
              [73, 8, 3215, 55, 927],
              [711, 632, 71]
             ]

padded_inputs = pad_sequences(raw_inputs,padding='post')

padded_inputs

array([[  83,   91,    1,  645, 1253,  927],
       [  73,    8, 3215,   55,  927,    0],
       [ 711,  632,   71,    0,    0,    0]])

In [53]:
# padding

a = [[24],
     [24, 34],
     [24, 34, 1],
     [24, 34, 1, 9],
     [24, 34, 1, 9, 56],
     [24, 34, 1, 9, 56, 76],
     [24, 34, 1, 9, 56, 76, 90],
     [24, 34, 1, 9, 56, 76, 90, 11],
     [24, 34, 1, 9, 56, 76, 90, 11, 67],
     [24, 34, 1, 9, 56, 76, 90, 11, 67, 54],
     [24, 34, 1, 9, 56, 76, 90, 11, 67, 54, 14]]

import numpy as np
np.max([len(x) for x in a])

row = 11
column = len(a)

tensor = np.zeros((row,column))

for i in range(len(a)):
    lst = a[i]
    for j in range(len(lst)):
        tensor[i][j] = lst[j]
tensor

array([[24.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  9., 56.,  0.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  9., 56., 76.,  0.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  9., 56., 76., 90.,  0.,  0.,  0.,  0.],
       [24., 34.,  1.,  9., 56., 76., 90., 11.,  0.,  0.,  0.],
       [24., 34.,  1.,  9., 56., 76., 90., 11., 67.,  0.,  0.],
       [24., 34.,  1.,  9., 56., 76., 90., 11., 67., 54.,  0.],
       [24., 34.,  1.,  9., 56., 76., 90., 11., 67., 54., 14.]])

In [54]:
# Pad Sequence (Pre)

from tensorflow.keras.preprocessing.sequence import pad_sequences

raw_inputs = [[83, 91, 1, 645, 1253, 927],
              [73, 8, 3215, 55, 927],
              [711, 632, 71]]

padded_inputs = pad_sequences(raw_inputs,padding='pre')

padded_inputs

array([[  83,   91,    1,  645, 1253,  927],
       [   0,   73,    8, 3215,   55,  927],
       [   0,    0,    0,  711,  632,   71]])

In [55]:
# Pad Sequence (Post)

raw_inputs = [[83, 91, 1, 645, 1253, 927],
              [73, 8, 3215, 55, 927],
              [711, 632, 71]]

padded_inputs = pad_sequences(raw_inputs,padding='post')

padded_inputs

array([[  83,   91,    1,  645, 1253,  927],
       [  73,    8, 3215,   55,  927,    0],
       [ 711,  632,   71,    0,    0,    0]])

In [56]:
# N Gram from Sequence List

lst = [24,34,1,9,56,76,90,11,67,54,14]

data = []

for i in range(0,len(lst)):
    print(lst[:i+1])
    data.append(lst[:i+1])

# Padding
pad_sequences(data,padding='post')

[24]
[24, 34]
[24, 34, 1]
[24, 34, 1, 9]
[24, 34, 1, 9, 56]
[24, 34, 1, 9, 56, 76]
[24, 34, 1, 9, 56, 76, 90]
[24, 34, 1, 9, 56, 76, 90, 11]
[24, 34, 1, 9, 56, 76, 90, 11, 67]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54, 14]


array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54, 14]])

In [57]:
# Truncating Sequence (Pre)

import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

data_vec = [['3', '18', '9', '3', '11', '5', '20'],
            ['3', '8', '1', '12'],
            ['18', '1', '8', '1'],
            ['8', '1', '9', '14'],
            ['25', '1', '8', '1'],
            ['9','3']]

# truncate sequence
truncated= pad_sequences(data_vec, maxlen=2)
print(truncated)

[[ 5 20]
 [ 1 12]
 [ 8  1]
 [ 9 14]
 [ 8  1]
 [ 9  3]]


In [58]:
# Truncating Sequence (Post)

# truncate sequence
truncated= pad_sequences(data_vec, maxlen=2,truncating='post')
print(truncated)

[[ 3 18]
 [ 3  8]
 [18  1]
 [ 8  1]
 [25  1]
 [ 9  3]]


In [ ]:
# Frequency Distribution

In [59]:
# Union

document1 = ['Hi', 'How','are','You', 'I','am']
document2 = ['Hello','I','am','fine','How','about','You']

#Union : words from two documents
print("Union",set(document1) | set(document2))

Union {'fine', 'How', 'about', 'Hello', 'are', 'Hi', 'am', 'You', 'I'}


In [60]:
# Intersection

document1 = ['Hi', 'How','are','You', 'I','am']
document2 = ['Hello','I','am','fine','How','about','You']

#Intersection : common words across two documents
print("Intersection:",set(document1) & set(document2))       
            

Intersection: {'I', 'am', 'How', 'You'}


In [61]:
# Generate Input for the RNN
import numpy as np

def name_intensor(name):
    name_in_tensor = np.zeros((len(name),1,n_letters))
    
    for i,letter in enumerate(name):
        name_in_tensor[i][0][all_letters.find(letter)] = 1
    
    return name_in_tensor

print("Example 1")
print(name_intensor('a'))
print(name_intensor('a').shape)

print("\n\n")

print("Example 2")
print(name_intensor('af'))
print(name_intensor('af').shape)

print("\n\n")

print("Example 3")
print(name_intensor('anand'))
print(name_intensor('anand').shape)

Example 1
[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(1, 1, 57)



Example 2
[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(2, 1, 57)



Example 3
[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 

In [62]:
# Conversion of Dimention of data : specially for LSTM

# Ex : list to array of (6,) to (1,1,6)

import numpy as np

one_hot1 = [[0,0,0,1,0,0],
           [0,0,0,1,0,1],
           [0,1,0,1,0,0]]# This is List of list type

one_hot2 = [[0,0,0,1,0,0],
           [0,0,0,1,0,1],
           [0,1,0,1,0,0]]# This is List of list type

# convert to format it can be used in the LSTM input

liss = [one_hot1,one_hot2]

np.asarray(liss).shape

(2, 3, 6)

In [7]:
from nltk.translate.api import AlignedSent

algnsent = AlignedSent(['klein', 'ist', 'das', 'Haus'], ['the', 'house', 'is', 'small'])

print(algnsent.words)

print(algnsent.mots)

algnsent.alignment

['klein', 'ist', 'das', 'Haus']
['the', 'house', 'is', 'small']


Alignment([])

In [8]:
# Lexical translation model that ignores word orde
# It is Used for Machine Translation


import pandas as pd
from nltk.translate.ibm1 import IBMModel1
from nltk.translate.api import AlignedSent

bitext = []

bitext.append(AlignedSent(['klein', 'ist', 'das', 'haus'], ['the', 'house', 'is', 'small']))

bitext.append(AlignedSent(['das', 'haus', 'ist', 'ja', 'groß'], ['the', 'house', 'is', 'big']))

bitext.append(AlignedSent(['das', 'buch', 'ist', 'ja', 'klein'], ['the', 'book', 'is', 'small']))

bitext.append(AlignedSent(['das', 'haus'], ['the', 'house']))

bitext.append(AlignedSent(['das', 'buch'], ['the', 'book']))

bitext.append(AlignedSent(['ein', 'buch'], ['a', 'book']))

ibm1 = IBMModel1(bitext, 5)

print(ibm1.translation_table['buch']['book'])

print(ibm1.translation_table['das']['book'])

print(ibm1.translation_table['buch'][None])

print(ibm1.translation_table['ja'][None])

test_sentence = bitext[2]

print(test_sentence.words)

print(test_sentence.mots)

test_sentence.alignment

0.8890388023094323
0.061668228784061314
0.11318685275683199
0.07278526278031176
['das', 'buch', 'ist', 'ja', 'klein']
['the', 'book', 'is', 'small']


Alignment([(0, 0), (1, 1), (2, 2), (3, 2), (4, 3)])

In [63]:
# Embedding of the Characters in the string : for LSTM

import numpy as np

word_vec_length = 10 # maximum length of the name

char_to_int = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 
               'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 
               'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 
               'w': 22, 'x': 23, 'y': 24, 'z': 25, 'ö': 26, 'ä': 27, 'ü': 28,
               '-': 29, 'ß': 30, ' ': 31}

char_vec_length = len(char_to_int)


# Returns a list of n lists with n = word_vec_length
def name_encoding(name):

    # Encode input data to int, e.g. a->1, z->26
    integer_encoded = [char_to_int[char] for i, char in enumerate(name) if i < word_vec_length]
    
    # Start one-hot-encoding
    onehot_encoded = list()
    
    for value in integer_encoded:
        # create a list of n zeros, where n is equal to the number of accepted characters
        letter = [0 for _ in range(char_vec_length)]
        letter[value] = 1
        onehot_encoded.append(letter)
        
    # Fill up list to the max length. Lists need do have equal length to be able to convert it into an array
    for _ in range(word_vec_length - len(name)):
        onehot_encoded.append([0 for _ in range(char_vec_length)])
        
    return onehot_encoded

names = ['santhosh','anand','sachin','prashanth']

# use asarray to use change the shape of the array which suits for LSTM
enc = np.asarray([np.asarray(name_encoding(name)) for name in names])

print(enc.shape)

enc

(4, 10, 32)


array([[[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

In [64]:
names = ["santhosh","kumar","anand","joshi"] # Samples

import string
import numpy as np

# get the alphabest
string.ascii_lowercase

# List of Vocabulary
vocabs_ = [x for x in string.ascii_lowercase] # Features

# vocabulary length
vocab_length = len(string.ascii_lowercase)

# Max Sequence Length
max_seq_length = max([len(x) for x in names])

char_2_int = {} 
int_2_char = {}

# Char to Interger 
char_2_int = dict([(x,i) for i,x in enumerate(vocabs_)])

# Integer to Char
int_2_char = dict([(i,x) for i,x in enumerate(vocabs_)])

# Create Zero array for encoding

encoding = np.zeros((len(names),max_seq_length,vocab_length))

print(encoding.shape)  # (4 Samples,max length of samples,vocabulary Length

# Update the encoder matrix for the samples

for i,name in enumerate(names): # i = index value and i = sample and j =time step
    for j,char in enumerate(name):
        encoding[i,j,char_2_int[char]] = 1.0
        
encoding

(4, 8, 26)


array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0

In [25]:
# Building Word Embedding Using Word Projection

import numpy as np

v = ["duct", "tape", "work", "anywher", "magic", "worship"]

np.random.seed(42)

input_array_tape=np.array([0,1,0,0,0,0]) #"tape"

input_weight_matrix = np.random.random_sample((6,3))

projection = np.dot(input_array_tape,input_weight_matrix)

print("projection:",projection)

output_weight_matrix = np.random.random_sample((3,6))

print("\n")
print("output_weight_matrix:",output_weight_matrix)

output_array_for_input_tape_and_orange_output_context = np.dot(projection, output_weight_matrix)

print("\n")
print("output_array_for_input_tape_and_orange_output_context:",output_array_for_input_tape_and_orange_output_context)

print("\n")
print(list(zip(v, output_array_for_input_tape_and_orange_output_context)))


projection: [0.59865848 0.15601864 0.15599452]


output_weight_matrix: [[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]


output_array_for_input_tape_and_orange_output_context: [0.42451664 0.32344971 0.40759145 0.31176029 0.41795589 0.35267831]


[('duct', 0.42451663675598933), ('tape', 0.32344971050993737), ('work', 0.4075914505752598), ('anywher', 0.3117602853605092), ('magic', 0.41795589389125587), ('worship', 0.35267831257488347)]


In [65]:
# CBOW

from tensorflow.keras.preprocessing import text

norm_bible = ['beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters']

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

wids = [[w for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters']]

In [66]:
from tensorflow.keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

word2id

# build vocabulary of unique words

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[[5, 1, 6, 7, 2], [2, 8, 9, 10, 11, 3, 4, 12], [13, 1, 14, 3, 4, 15]]

In [67]:
vocab_size = len(word2id)
embed_size = 100
window_size = 2 # context window size

vocab_size

16

In [68]:
window_size = 2

for words in wids:
    print(words)
    sentence_length = len(words)
    for index,word in enumerate(words):
        print("sentence_length:",sentence_length)
        print("WindowSize:",window_size)
        print("index:",index)
        print("Word at index {0} : '{1}'".format(index,word))
        
        context_words =[]
        context_words1 = []
       
        print("start = index - window_size")
        print("end = index + window_size + 1")
        
        start = index - window_size
        end = index + window_size + 1
        

        print("start:",start)
        print("end:",end)
       
        print("Choosing context word based on condition:")
        
        print([x for x in range(start, end)])
        for i in range(start, end):
            
            print("range index:",i)
            
            if 0 <= i:
                print("Statisfied the condition '0 <= i' ")
                
                if i < sentence_length:
                    print("Statisfied the condition 'i < sentence_length' ")
                    
                    if i != index:
                        print("Statisfied the condition 'i != index'")
                        print("Selected Word: '{0}'".format(words[i]))
            
            if  0 <= i < sentence_length and i != index:
                print("Word at range index at {0} is '{1}'".format(i,words[i]))
                context_words.append(words[i])
                
        
        print("Input:",context_words)   
        print("Output:",words[index])
        
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")

    
        context_words1.append([words[i] for i in range(start, end) if 0 <= i < sentence_length and i != index])
        
        
        
        print("context_words :",context_words)
        print("context_words1 :",context_words1)
        print("*****************************")
    print("###############################################################################")

[5, 1, 6, 7, 2]
sentence_length: 5
WindowSize: 2
index: 0
Word at index 0 : '5'
start = index - window_size
end = index + window_size + 1
start: -2
end: 3
Choosing context word based on condition:
[-2, -1, 0, 1, 2]
range index: -2
range index: -1
range index: 0
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
range index: 1
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
Statisfied the condition 'i != index'
Selected Word: '1'
Word at range index at 1 is '1'
range index: 2
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
Statisfied the condition 'i != index'
Selected Word: '6'
Word at range index at 2 is '6'
Input: [1, 6]
Output: 5
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
context_words : [1, 6]
context_words1 : [[1, 6]]
*****************************
sentence_length: 5
WindowSize: 2
index: 1
Word at index 1 : '1'
start = index - window_size
end =

In [70]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.utils import to_categorical

window_size = 2

def generator():
    for words in wids:
        sentence_length = len(words)
        for index,word in enumerate(words):
            context_words =[]
            label_word = []

            start = index - window_size
            end = index + window_size + 1

            context_words.append([words[i] for i in range(start, end) if 0 <= i < sentence_length and i != index])

            label_word.append(word)
            
            x = sequence.pad_sequences(context_words, maxlen=7)
            y = to_categorical(label_word, vocab_size)

            yield (x, y)

In [71]:
for x ,y in generator():
    print("input: {0}  output: {1}".format(x,y))

input: [[0 0 0 0 0 1 6]]  output: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 5 6 7]]  output: [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 5 1 7 2]]  output: [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 1 6 2]]  output: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 0 6 7]]  output: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 0 8 9]]  output: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  0  2  9 10]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  2  8 10 11]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  8  9 11  3]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  9 10  3  4]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
input: [[ 0  0  0 10 11  4 12]]  output: [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  

In [ ]:
# Skip Gram

In [72]:
from tensorflow.keras.preprocessing.sequence import skipgrams

# generate skip-grams
skip_grams = [skipgrams(wid, vocabulary_size=vocab_size, window_size=10) for wid in wids]

# view sample skip-grams
pairs, labels = skip_grams[0][0], skip_grams[0][1]
for i in range(10):
    print("({:s} ({:d}), {:s} ({:d})) -> {:d}".format(
          id2word[pairs[i][0]], pairs[i][0], 
          id2word[pairs[i][1]], pairs[i][1], 
          labels[i]))

(heaven (7), earth (2)) -> 1
(heaven (7), beginning (5)) -> 1
(god (1), waters (15)) -> 0
(earth (2), without (8)) -> 0
(created (6), earth (2)) -> 1
(beginning (5), heaven (7)) -> 1
(created (6), void (10)) -> 0
(created (6), darkness (11)) -> 0
(heaven (7), beginning (5)) -> 0
(god (1), earth (2)) -> 1


In [73]:
from tensorflow.keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)

word2id = tokenizer.word_index
id2word = {v:k for k, v in word2id.items()}

vocab_size = len(word2id) + 1 
embed_size = 100

wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]
print('Vocabulary Size:', vocab_size)
print('Vocabulary Sample:', list(word2id.items())[:10])

Vocabulary Size: 16
Vocabulary Sample: [('god', 1), ('earth', 2), ('upon', 3), ('face', 4), ('beginning', 5), ('created', 6), ('heaven', 7), ('without', 8), ('form', 9), ('void', 10)]


In [75]:
# Using Glove : Pretained Word Embedding

from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer

corpus = [
            'This is an excellent movie',
            'The move was fantastic I like it',
            'You should watch it is brilliant',
            'Exceptionally good',
            'Wonderfully directed and executed I like it',
            'Its a fantastic series',
            'Never watched such a brillent movie',
            'It is a Wonderful movie',
        ]

word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)


In [76]:
vocab_length = len(word_tokenizer.word_index) + 1

print(vocab_length)

31


In [83]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)

embedded_sentences

[[8, 2, 9, 10, 3],
 [11, 12, 13, 5, 6, 7, 1],
 [14, 15, 16, 1, 2, 17],
 [18, 19],
 [20, 21, 22, 23, 6, 7, 1],
 [24, 4, 5, 25],
 [26, 27, 28, 4, 29, 3],
 [1, 2, 4, 30, 3]]

In [ ]:
from nltk.tokenize import word_tokenize

import nltk
nltk.download('punkt')
from tensorflow.keras.preprocessing.sequence import pad_sequences

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')

print(padded_sentences)

In [ ]:
# Loading Pretrained Word Embeddings : Glove

# The smallest file is named "Glove.6B.zip". The size of the file is 822 MB. 
# The file contains 50, 100, 200, and 300 dimensional word vectors for 400k words. We will be using the 100 dimensional vector.

In [90]:
from numpy import array
from numpy import asarray
from numpy import zeros

# Empty dictionary that will store our word embeddings
embeddings_dictionary = dict()

# Loading the Pretrained Glove Word Embedding Model
glove_file = open('glove.6B.100d.txt', encoding="utf8")

#  Here notice that we loaded glove.6B.100d.txt file. This file contains 100 dimensional word embeddings. 
# We will create a dictionary that will contain words as keys and the corresponding 100 dimensional vectors as values, 
#  in the form of an array.

for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary [word] = vector_dimensions
    
glove_file.close()

In [91]:
# The dictionary embeddings_dictionary now contains words and corresponding GloVe embeddings for all the words

embeddings_dictionary['the']

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [92]:
embeddings_dictionary['at']

array([ 0.1766   ,  0.093851 ,  0.24351  ,  0.44313  , -0.39037  ,
        0.12524  , -0.19918  ,  0.59855  , -0.82035  ,  0.28006  ,
        0.54231  ,  0.023079 ,  0.12837  , -0.044489 ,  0.3837   ,
       -0.75659  ,  0.40254  , -0.4462   , -0.81599  , -0.0091513,
        0.65219  , -0.043656 ,  0.54919  , -0.16696  ,  0.73028  ,
       -0.20703  , -0.069863 , -0.31259  ,  0.27226  ,  0.084905 ,
       -0.60498  ,  0.42826  ,  0.60134  ,  0.50953  , -0.39073  ,
        0.44608  , -0.36331  ,  0.50858  , -0.20308  , -0.43503  ,
       -0.086827 , -0.86581  , -1.0151   , -0.35725  , -0.12993  ,
        0.3324   ,  0.3026   ,  0.067277 , -0.52948  , -0.81223  ,
        0.39562  , -0.79537  ,  0.24331  ,  1.2506   , -1.0169   ,
       -3.3391   , -0.79691  , -0.33877  ,  1.366    ,  0.87513  ,
       -0.63701  ,  0.68381  , -0.057432 ,  0.12541  , -0.8258   ,
       -0.56117  ,  0.30807  ,  0.1545   ,  0.61473  ,  0.67403  ,
       -0.60833  , -0.25911  , -0.35619  , -0.71189  , -0.3120

In [96]:
# Creating word embedding for our Corpus

corpus = [
            'This is an excellent movie',
            'The move was fantasti',
        ]

word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)

embedding_matrix = zeros((vocab_length, 100))

for word,index in word_tokenizer.word_index.items():
    print("word:{0} and index:{1}".format(word,index))
    print(embeddings_dictionary.get(word))
    
    embedding_vector = embeddings_dictionary.get(word)
    
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector

word:this and index:1
[-0.57058   0.44183   0.70102  -0.41713  -0.34058   0.02339  -0.071537
  0.48177  -0.013121  0.16834  -0.13389   0.040626  0.15827  -0.44342
 -0.019403 -0.009661 -0.046284  0.093228 -0.27331   0.2285    0.33089
 -0.36474   0.078741  0.3585    0.44757  -0.2299    0.18077  -0.6265
  0.053852 -0.29154  -0.4256    0.62903   0.14393  -0.046004 -0.21007
  0.48879  -0.057698  0.37431  -0.030075 -0.34494  -0.29702   0.15095
  0.28248  -0.16578   0.076131 -0.093016  0.79365  -0.60489  -0.18874
 -1.0173    0.31962  -0.16344   0.54177   1.1725   -0.47875  -3.3842
 -0.081301 -0.3528    1.8372    0.44516  -0.52666   0.99786  -0.32178
  0.033462  1.1783   -0.072905  0.39737   0.26166   0.33111  -0.35629
 -0.16558  -0.44382  -0.14183  -0.37976   0.28994  -0.029114 -0.35169
 -0.27694  -1.344     0.19555   0.16887   0.040237 -0.80212   0.23366
 -1.3837   -0.023132  0.085395 -0.74051  -0.073934 -0.58838  -0.085735
 -0.10525  -0.51571   0.15038  -0.16694  -0.16372  -0.22702  -0.6610

In [97]:
embedding_matrix.shape

# 31 : My corpus Vocabulary
# 100 : Dimention of the word

(31, 100)

In [99]:
# Word2Vec Using gensim Model

from gensim.models import Word2Vec

norm_bible = ['beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters']

norm_bible = [x.split() for x in norm_bible]

norm_bible

[['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters']]

In [100]:
# Vocabulary
_vocab = set([x for y in norm_bible for x in y])

_vocab

{'beginning',
 'created',
 'darkness',
 'deep',
 'earth',
 'face',
 'form',
 'god',
 'heaven',
 'moved',
 'spirit',
 'upon',
 'void',
 'waters',
 'without'}

In [101]:
# Vocab size
len(_vocab)

15

In [102]:
# Building the Word2Vec 

model = Word2Vec(sentences=norm_bible, max_vocab_size=100, window=5, min_count=1, workers=4)

In [103]:
# model.save("word2vec.model")
# model = Word2Vec.load("word2vec.model")

In [104]:
# If you save the model you can continue training it later:
model.train([["hello", "world"]], total_examples=1, epochs=1)

(0, 2)

In [105]:
model.wv.get_vector('heaven', norm=True)

array([-0.03288836, -0.08910534,  0.15980722, -0.15729724,  0.0761887 ,
        0.09141698, -0.02383908,  0.15236385,  0.1672206 , -0.09261578,
       -0.10185118, -0.11413173, -0.13354973, -0.05155852, -0.09462849,
       -0.14115852,  0.01324356,  0.05065757,  0.10851171, -0.0444713 ,
       -0.07533497,  0.02113773,  0.00662196,  0.13730705,  0.00309225,
        0.12232942, -0.13980244,  0.14266157, -0.03195277,  0.14718859,
       -0.12884632,  0.03038765,  0.01787149,  0.00077822, -0.08632658,
       -0.15643395, -0.12288143, -0.13450196,  0.03237257,  0.00809372,
       -0.03067101,  0.12044464, -0.04187879, -0.02279109, -0.15056182,
       -0.16789816,  0.15138787, -0.09733356, -0.10780554,  0.08795309,
        0.11282953, -0.11556396,  0.01623527, -0.10163928,  0.02786644,
       -0.07255738, -0.05820448,  0.03697271,  0.14651914,  0.11381263,
       -0.16369697, -0.09510347,  0.13330361,  0.03365194, -0.07199534,
        0.0101295 ,  0.16105644, -0.01865355, -0.15942708,  0.02

In [ ]:
# Bulding the vector : Numpy array for the word 

model.wv['god']  # get numpy vector of a word

In [ ]:
model.wv['god','heaven']  # get numpy vector of a word

In [ ]:
# get other similar words

sims = model.wv.most_similar('god', topn=10)  

sims

In [ ]:
# Difference between Word2Vec and Doc2Vec
# 1. As the names suggest Word2Vec is trained on single words while Doc2vec is trained texts of variable length,

# Glove and word2vec, these are unsupervised approaches for building vectors from text data.
# The main difference is the functioning of both models. Glove is Count based model, and Word2vec is predictive modeling
