In [16]:
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer

corpus = [
            'This is an excellent movie',
            'The move was fantastic I like it',
            'You should watch it is brilliant',
            'Exceptionally good',
            'Wonderfully directed and executed I like it',
            'Its a fantastic series',
            'Never watched such a brillent movie',
            'It is a Wonderful movie',
        ]

word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)

In [18]:
    vocab_length = len(word_tokenizer.word_index) + 1

    print(vocab_length)

44


In [20]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)

embedded_sentences

[[14, 3, 15, 16, 1],
 [4, 17, 6, 9, 5, 7, 2],
 [18, 19, 20, 2, 3, 21],
 [22, 23],
 [24, 25, 26, 27, 5, 7, 2],
 [28, 8, 9, 29],
 [30, 31, 32, 8, 33, 1],
 [2, 3, 8, 34, 1],
 [10, 11],
 [35, 36, 37],
 [12, 38],
 [2, 6, 39, 40],
 [5, 41, 13, 7, 4, 1],
 [4, 1, 6, 10],
 [5, 42, 13, 43],
 [4, 11, 3, 12]]

In [22]:
from nltk.tokenize import word_tokenize
from keras.preprocessing.sequence import pad_sequences

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')

print(padded_sentences)

[[14  3 15 16  1  0  0]
 [ 4 17  6  9  5  7  2]
 [18 19 20  2  3 21  0]
 [22 23  0  0  0  0  0]
 [24 25 26 27  5  7  2]
 [28  8  9 29  0  0  0]
 [30 31 32  8 33  1  0]
 [ 2  3  8 34  1  0  0]
 [10 11  0  0  0  0  0]
 [35 36 37  0  0  0  0]
 [12 38  0  0  0  0  0]
 [ 2  6 39 40  0  0  0]
 [ 5 41 13  7  4  1  0]
 [ 4  1  6 10  0  0  0]
 [ 5 42 13 43  0  0  0]
 [ 4 11  3 12  0  0  0]]


In [13]:
# Loading Pretrained Word Embeddings : Glove

# The smallest file is named "Glove.6B.zip". The size of the file is 822 MB. 
# The file contains 50, 100, 200, and 300 dimensional word vectors for 400k words. We will be using the 100 dimensional vector.

In [ ]:
from numpy import array
from numpy import asarray
from numpy import zeros

In [3]:
# Empty dictionary that will store our word embeddings
embeddings_dictionary = dict()

glove_file = open('C:/MyWork/MyLearning/Career Growth/ML/Files/DataSet/glove.6B.100d.txt', encoding="utf8")

In [7]:
#  Here notice that we loaded glove.6B.100d.txt file. This file contains 100 dimensional word embeddings. 

for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary [word] = vector_dimensions
    
glove_file.close()

In [11]:
# The dictionary embeddings_dictionary now contains words and corresponding GloVe embeddings for all the words

In [33]:
embedding_matrix = zeros((vocab_length, 100))

for word,index in word_tokenizer.word_index.items():
    print("word:{0} and index:{1}".format(word,index))
    print(embeddings_dictionary.get(word))
    
    embedding_vector = embeddings_dictionary.get(word)
    
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector


word:movie and index:1
[ 0.38251    0.14821    0.60601   -0.51533    0.43992    0.061053
 -0.62716   -0.025385   0.1643    -0.22101    0.14423   -0.37213
 -0.21683   -0.08895    0.097904   0.6561     0.64455    0.47698
  0.83849    1.6486     0.88922   -0.1181    -0.012465  -0.52082
  0.77854    0.48723   -0.014991  -0.14127   -0.34747   -0.29595
  0.1028     0.57191   -0.045594   0.026443   0.53816    0.32257
  0.40788   -0.043599  -0.146     -0.48346    0.32036    0.55086
 -0.76259    0.43269    0.61753   -0.36503   -0.60599   -0.79615
  0.3929    -0.23668   -0.34719   -0.61201    0.54747    0.94812
  0.20941   -2.7771    -0.6022     0.8495     1.2549     0.017893
 -0.041901   2.1147    -0.026618  -0.28104    0.68124   -0.14165
  0.99249    0.49879   -0.67538    0.6417     0.42303   -0.27913
  0.063403   0.68909   -0.36183    0.053709  -0.16806    0.19422
 -0.47073   -0.14803   -0.58986   -0.2797     0.16792    0.10568
 -1.7601     0.0088254 -0.83326   -0.5836    -0.37079   -0.56591


In [26]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.38251001,  0.14821   ,  0.60601002, ...,  0.058921  ,
         0.091112  ,  0.47283   ],
       [-0.30664   ,  0.16821   ,  0.98510998, ..., -0.38775   ,
         0.36916   ,  0.54521   ],
       ...,
       [ 0.30449   , -0.19628   ,  0.20225   , ..., -0.18385001,
        -0.12432   ,  0.27467999],
       [-0.26703   ,  0.44911   ,  0.55478001, ..., -0.87247002,
         0.83828002,  0.465     ],
       [-0.57547998, -0.043236  , -0.1972    , ..., -0.10507   ,
         0.26554999,  0.32192999]])

In [34]:
embedding_matrix.shape

(44, 100)

In [ ]:
# 44 : My corpus Vocabulary
# 100 : Dimention of the word